theme: jekyll-theme-dinky
title: Rylan Henry's Techstart Portfolio
description: Hi, my name is Rylan Henry, and I go to Pinnicle View Middle School. I'm in sixth grade and I'm 11 years old and I play two sports.
description: I love memes, South Park, Rick and Morty, comedy, and video games. 
